language: php

sudo: false

notifications:
    email: false

branches:
    only:
        - master

dist: precise

matrix:
    fast_finish: true
    include:
    - php: 5.2
      env: WP_VERSION=latest RUN_CODE_COVERAGE=0
    - php: 5.6
      env: WP_VERSION=latest RUN_CODE_COVERAGE=0
    - php: 7.0
      env: WP_VERSION=latest RUN_CODE_COVERAGE=1
    - php: 7.1
      env: WP_VERSION=latest RUN_CODE_COVERAGE=0

before_script:
    - bash tests/bin/install.sh wcsat_test root '' localhost $WP_VERSION release/3.2
    - bash tests/bin/travis.sh before

script:
    - bash tests/bin/phpunit.sh

    # Search for PHP syntax errors.
    - find . \( -path ./tmp -o -path ./tests \) -prune -o \( -name '*.php' \) -exec php -lf {} \;

after_script:
    - bash tests/bin/travis.sh after
